# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1baf6bbc64bad7abbc1cce68a7418946d6750f16948a635b793124be78ae8bd56e7124573b24fafcace9e25d0030ee7b224da46794780a1a38014f5cf7dce728

test:
  secret_key_base: 8b508cbdedc9f8a1c6755df9f847449c7271d4cab3f2ec531236ef5bb6f4ac6987d42f7670b1d42796eca656574558f2dd7a27292cf28eeca07e6d41817d9ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
